server.port: 7001
server.error.include-message: always

spring.data.mongodb:
  auto-index-creation: true
  host: localhost
  port: 27017
  database: product-


logging:
  level:
    root: INFO
    se.magnus: DEBUG

---
spring.profiles: docker
spring.data.mongodb.host: mongodb
server.port: 8080
